### ISSUE TITLE
Why is click version less than 7 required?

### ISSUE THREAD

**Issue by metaperl** [di/bump#12]
Click is [currently at version 7.1.2](https://pypi.org/project/click/).

The [setup.py requires a version less than 7](https://github.com/di/bump/blob/master/setup.py#L25). 

Should this requirement be dropped/changed in some way?

**Comment by di** [comment]
Simply because it didn't exist when the sub-dependency was set.

Feel free to make a PR to upgrade this to `>=6,<8`!

**Comment by di** [comment]
Fixed in https://github.com/di/bump/pull/13.
