### ISSUE TITLE
patch level increases when minor/major are specified?

### ISSUE THREAD

**Issue by metaperl** [di/bump#15]
In [the code](https://github.com/di/bump/blob/master/bump.py#L114) we can see:

```python
        patch = patch or config.getboolean("bump", "patch", fallback=True)
```

which means that `patch` will be true unless specified.

This means that if the current version is `1.1.1` and you do `bump --minor` the new version is `1.2.2` instead of `1.2.1`

Is this behavior intended? If so, why?

**Comment by metaperl** [comment]
# How to produce this "problem"

1. Download [the zip master](https://github.com/di/bump/archive/master.zip) and then unpack it.
1. Install bump via `pip install bump`
1. change to the directory of the unpacked zip
1. Type `bump --minor` or `bump --major`

Note that the **Patch** level increased even though not specified.

**Comment by di** [comment]
This was the original behavior of the library (I am not the original author)

**Comment by di** [comment]
Hi @metaperl, @claudinoac is proposing #16 to resolve this, would you like to take a look?

**Comment by di** [comment]
Released in https://pypi.org/project/bump/1.3.0/.
