### ISSUE TITLE
Add `pypi` arg to get information about latest version from the pypi.org

### ISSUE THREAD

**Issue by NexSabre** [di/bump#19]
## Problem:
* When publishing the application, remember to change the major/minor version, but when publishing a patch, you may forget to update the patch version, 
* Developers are sometimes lazy and don't bump up the version for every patch.

## Solution:
By adding the command `bump --pypi` during the build and release process, the script will take the number from` pypi.org` and increment it by one, patch number.

Example:
Local version `1.3.0`, pypi version `1.4.0`, after the `bump --pypi` `1.4.1`.

This only leaves the user with the responsibility of keeping the numbers for major / minor. 

Proposition of the change in PR #19

**Comment by di** [comment]
Thanks for filing the issue!

I'm not sure I understand why the local version would be lower than what's on PyPI? Why would it be `1.3.0` and not `1.4.0`?

**Comment by NexSabre** [comment]
My mistake, this is an inaccurate example.
When we're implementing patches and we don't want to waste time changing patch numbers. It's enough for us to set minor/major and we don't want to add to our process that every time CI builds a package for us, it commits a change to the code with a new number.

We can then set myself to version 1.4.0 and all patches will be numbered via pypi.org.

**Comment by di** [comment]
Wouldn't this just be the same as bumping with `bump --patch`? Why would the local version be different than what's on PyPI?

**Comment by NexSabre** [comment]
The result for the first iteration will be the same as with `--patch`, but when we do it next time (and more without manually bumbing version), we can get a conflict at uploading file with the same version to the pypi.

**Comment by di** [comment]
The usual workflow would be something like:

* make some changes
* run bump
* commit/push/merge the changes
* publish to pypi

That way whatever the version is, either locally, in your repo or CI environment, it's the same as the latest version on PyPI.

Based on that, I'm not sure what the scenario where running `bump --patch` one or multiple times would produce a version that's already on PyPI -- can you explain how that would happen?

**Comment by NexSabre** [comment]
Sometimes we don't have the option of adding new versions to the code in the building process (pipeline is forbidden to use write access), and sometimes we forget to raise the patch version.

We originally used it with Artifactory, now I adapted it to pypi.org.

I added an additional condition:
```text
local   |   pypi.org  |  after update 
1.2.9   |    1.3.0    |  -> 1.3.1
1.3.0   |    1.3.0    |  -> 1.3.1
1.3.0   |    1.3.1    |  -> 1.3.2
1.4.0   |    1.3.0    |  -> 1.4.0
```

**Comment by di** [comment]
So you're increasing the version number when publishing, but not adding it back to the source code? Why not just ensure the version number is increased whenever changes are made?

This tool is primarily focused on taking the local source as the source of truth, and then bumping it. Introducing the potential for the current state on PyPI (or any other index) to change how this works is somewhat counter to the goals, I'm not sure if this is a use case it makes sense to support.

**Comment by NexSabre** [comment]
Ok, no problem, I'll keep this change in my fork. Closing issue and PR #18
